class VABs_Mode_Unselected {
    condition = C_COND(C_EQ(C_MPD_USER(MFD_IND_WPN_SELECTED_WPN), 0));
    MPD_ARROW_R(BORESIGHT, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_5_Y, 9)
    MPD_TEXT_R(BORESIGHT, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_5_Y, MPD_TEXT_STATIC("BORESIGHT"))
    MPD_TEXT_R(GRAYSCALE, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_6_Y, MPD_TEXT_STATIC("GRAYSCALE"))
};