class VABs_Mode_Unselected {
    condition =  __EVAL(format [STRINGIFY(EQ(user%1,0)), MFD_OFFSET + MFD_IND_WPN_SELECTED_WPN]);
    MPD_ARROW_R(BORESIGHT, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_5_Y, 9)
    MPD_TEXT_R(BORESIGHT, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_5_Y, MPD_TEXT_STATIC("BORESIGHT"))
    MPD_TEXT_R(GRAYSCALE, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_6_Y, MPD_TEXT_STATIC("GRAYSCALE"))
};