class VABS {
    //L5
    MPD_BOX_R(CM,  MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_5_Y, 2)
    MPD_TEXT_R(CM, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_5_Y, MPD_TEXT_STATIC("CM"))
    //L4
    MPD_BOX_R(HZ,  MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_4_Y, 2)
    MPD_TEXT_R(HZ, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_4_Y, MPD_TEXT_STATIC("HZ"))
    //L3
    MPD_BOX_R(WP,  MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_3_Y, 2)
    MPD_TEXT_R(WP, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_3_Y, MPD_TEXT_STATIC("WP"))
    //L2
    MPD_BOX_R(ADD,  MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_2_Y, 3)
    MPD_TEXT_R(ADD, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_2_Y, MPD_TEXT_STATIC("ADD"))
    //L1
    MPD_TEXT_R(POINT_Label, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_1_Y - 0.5 * MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("POINT>"))
    MPD_TEXT_R(POINT,       MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_1_Y + 0.5 * MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("W02"))
};