repos:
  - repo: local
    hooks:
    - id: path-validation
      name: Validate file paths
      description: Validate all file paths within PBOs to ensure consistency
      entry: python tools/checkFilePaths.py
      verbose: true
      language: python
      language_version: python3
      additional_dependencies: ['pyyaml']
      pass_filenames: false