from SCons.Script import *

import os.path
import glob
import winreg
import urllib.request
import os
import zipfile
import json
import subprocess
import tools.mfd_documentation.document as mfd_document

env = Environment(tools=[])

# Utility functions
def allFilesIn(path):
    return [s.replace("$", "$$") for s in glob.glob(path + '/**/*', recursive=True) if os.path.isfile(s)]

def getSettings():
    with open("tools/build.json") as file:
        settings = json.load(file)

    addons_folder = settings.get("addonsFolder", "addons")
    if not os.path.isdir(addons_folder):
        fallback = "addons"
        if os.path.isdir(fallback):
            print(f"Warning: addonsFolder '{addons_folder}' not found; using '{fallback}'")
            settings["addonsFolder"] = fallback
        else:
            raise FileNotFoundError(
                f"Configured addonsFolder '{addons_folder}' does not exist, and fallback '{fallback}' is missing."
            )

    return settings

def targetDefinition(target, description):
    return env.Help(f"\n{target.ljust(20)}\t - {description}")

def isJunction(path):
    process = subprocess.run(["fsutil", "reparsepoint", "query", path], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return process.returncode == 0

# Useful paths
def hemttPath():
    result = subprocess.run(["where", "hemtt"], capture_output=True)
    if result.returncode == 0:
        return result.stdout.decode('utf-8').splitlines()[0].strip()
    raise FileNotFoundError("HEMTT not found on PATH. Install from https://hemtt.dev/")

def arma3Path():
    reg = winreg.ConnectRegistry(None, winreg.HKEY_LOCAL_MACHINE)
    with winreg.OpenKey(reg, r"SOFTWARE\Wow6432Node\bohemia interactive\arma 3") as key:
        return winreg.EnumValue(key,1)[1]

class Object(object):
    pass

def getPboInfo(settings):
    def addInfo(name):
        pboInfo = Object()
        pboInfo.name = name
        pboInfo.folder = os.path.join(settings["addonsFolder"], name)
        with open(os.path.join(pboInfo.folder,"$PBOPREFIX$"), "r") as file:
            pboInfo.pboPrefix = file.readline().strip()
        try:
            pboInfo.a3symlink = os.path.join(arma3Path(),pboInfo.pboPrefix)
        except:
            pboInfo.a3symlink = None

        if (name in settings["excludePboSymlinks"]):
            pboInfo.a3symlink = None
        return pboInfo
    return list(map(addInfo,filter(lambda x: os.path.isdir(os.path.join(settings["addonsFolder"], x)), os.listdir(settings["addonsFolder"]))))

# Symlink management for file patching
def commandsToRemoveSymlink(pbo):
    if pbo.a3symlink is None:
        return []
    commands = []
    if isJunction(pbo.a3symlink):
        commands.append(f'fsutil reparsepoint delete \"{pbo.a3symlink}\"')
    if os.path.isdir(pbo.a3symlink):
        commands.append(Delete(pbo.a3symlink))
    return commands

def commandsToCreateSymlink(pbo):
    if pbo.a3symlink is None:
        return []
    commands = commandsToRemoveSymlink(pbo)
    if not os.path.isdir(os.path.dirname(pbo.a3symlink)):
        commands.append(Mkdir(os.path.dirname(pbo.a3symlink)))
    commands.append(f'mklink /J "{pbo.a3symlink}" "{pbo.folder}"')
    return commands

# Documentation
def downloadNaturaldocs(target, source, env):
    url = "https://www.naturaldocs.org/download/natural_docs/2.2/Natural_Docs_2.2.zip"
    zipFilePath = r"buildTools\NaturalDocs.zip"
    urllib.request.urlretrieve(url, zipFilePath)
    with zipfile.ZipFile(zipFilePath, 'r') as zip_ref:
        zip_ref.extractall(r"buildTools")

def generateMfdDocumentation(target, source, env):
    class Namespace:
        pass
    args = Namespace()
    args.output = "docs/other/mfdindices.html"
    args.filepath = os.path.join("addons", "fza_ah64_mpd", "headers", "mfdConstants.h")
    mfd_document.run(args)

settings = getSettings()
pbos = getPboInfo(settings)

env.Command("buildTools", [], Mkdir("buildTools"))

env.Command(r"buildTools\Natural Docs", [], [downloadNaturaldocs, Delete(r"buildTools\NaturalDocs.zip")])

# Build all PBOs using HEMTT (version.hpp generated by .hemtt/hooks/pre_build/version_files.rhai)
hemtt_exe = hemttPath()

def _hemttBuildAction(target, source, env):
    result = subprocess.run([hemtt_exe, "build"])
    return result.returncode

def _repackageReleaseZips():
    """
    Repackage release zips to rename the inner mod folder:
      - Inner folder: @fza_ah64  ->  @fza_ah64_apache_longbow
    The zip file rename (fza_ah64-*.zip -> ah64-*.zip) is handled by the
    HEMTT post_release hook (.hemtt/hooks/post_release/rename_zips.rhai)
    which runs as part of `hemtt release` before this function is called.
    """
    releases_dir = os.path.abspath("releases")
    old_folder = "@fza_ah64"
    new_folder = "@fza_ah64_apache_longbow"

    zips = glob.glob(os.path.join(releases_dir, "ah64-*.zip"))
    if not zips:
        print("No ah64-*.zip files found in releases/ — skipping inner folder repackage.")
        return

    for zip_path in zips:
        zip_name = os.path.basename(zip_path)
        temp_dir = os.path.join(releases_dir, "_repack_temp")
        if os.path.isdir(temp_dir):
            import shutil
            shutil.rmtree(temp_dir)

        print(f"Repackaging {zip_name} (renaming inner folder)...")
        with zipfile.ZipFile(zip_path, "r") as zf:
            zf.extractall(temp_dir)

        old_path = os.path.join(temp_dir, old_folder)
        if os.path.isdir(old_path):
            os.rename(old_path, os.path.join(temp_dir, new_folder))

        if os.path.isfile(zip_path):
            os.remove(zip_path)

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
            for root, dirs, files in os.walk(temp_dir):
                for file in files:
                    abs_path = os.path.join(root, file)
                    arc_name = os.path.relpath(abs_path, temp_dir)
                    zf.write(abs_path, arc_name)

        import shutil
        shutil.rmtree(temp_dir)
        print(f"  -> {zip_name} ({new_folder})")

def _hemttReleaseAction(target, source, env):
    result = subprocess.run([hemtt_exe, "release"])
    if result.returncode != 0:
        return result.returncode
    _repackageReleaseZips()
    return 0

hemttBuild = env.Command(
    ".hemttout",
    allFilesIn("addons"),
    [Action(_hemttBuildAction, f'"{hemtt_exe}" build')],
)
env.AlwaysBuild(hemttBuild)

hemttRelease = env.Command(
    "releases",
    allFilesIn("addons"),
    [Action(_hemttReleaseAction, f'"{hemtt_exe}" release')],
)
env.AlwaysBuild(hemttRelease)

allPbos = env.Alias("all", [hemttBuild])
targetDefinition("all", "Build all pbos via HEMTT.")

env.Alias("release", [hemttRelease])
targetDefinition("release", "Release via HEMTT (signs, archives).")

buildMfdDocs = env.Command(r"docs\other\mfdindices.html",
    [os.path.join("addons", "fza_ah64_mpd", "headers", "mfdConstants.h")],
    generateMfdDocumentation)
env.AlwaysBuild(buildMfdDocs)

buildDocs = env.Command(r"docs\index.html",
    [s for s in allFilesIn(settings["addonsFolder"]) if s.endswith(".sqf")] + [r"buildTools\Natural Docs"], 
    [Mkdir("docs"), r'"buildTools\Natural Docs\NaturalDocs.exe" naturaldocs'])
env.AlwaysBuild(buildDocs)

env.Alias("docs", [r"docs\index.html", r"docs\other\mfdindices.html"])
targetDefinition("docs", "Generate naturaldocs documentation")
env.Help("\n")
targetDefinition("-c / --clean", "Clean build outputs (.hemttout, releases, docs, buildTools).")
targetDefinition("-c release", "Clean release outputs only (.hemttout, releases).")

env.Clean(["buildTools", "all"], r"buildTools")
env.Clean(["docs", "all"], ["docs", r"naturaldocs\Working Data"])
env.Clean(["all", "release"], [".hemttout", "releases"])

try:
    settings = getSettings()
    a3dir = arma3Path()
    symlinks = env.Alias("symlinks", [], sum(map(commandsToCreateSymlink, pbos),[]))
    env.AlwaysBuild(symlinks)
    env.Help("\n")
    targetDefinition("symlinks", "Create Arma 3 junction links for each addon (enables file patching).")

    removeSymlinks = env.Alias("rmsymlinks", [], sum(map(commandsToRemoveSymlink, pbos),[]))
    env.AlwaysBuild(removeSymlinks)
    targetDefinition("rmsymlinks", "Remove Arma 3 junction links.")
    env.Help("\n")
except Exception as e:
    print(e)
    print("Error: Couldn't find arma 3, cannot make or remove symlinks")

env.Default("all")