class VABSBottom {
    //B3
    MPD_ARROW_C(ZN, MPD_POS_BUTTON_TB_3_X-0.015, MPD_POS_BUTTON_B_Y, 2)
    MPD_TEXT_C(ZN,  MPD_POS_BUTTON_TB_3_X-0.015, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC("ZN"))
    //B4
    MPD_ARROW_C(WPT, MPD_POS_BUTTON_TB_4_X+0.015, MPD_POS_BUTTON_B_Y, 3)
    MPD_TEXT_C(WPT,  MPD_POS_BUTTON_TB_4_X+0.015, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC("WPT"))
    //B5
    MPD_ARROW_C(RTR, MPD_POS_BUTTON_TB_5_X, MPD_POS_BUTTON_B_Y, 3)
    MPD_TEXT_C(RTE,  MPD_POS_BUTTON_TB_5_X, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC("RTE"))
    //B6
    MPD_ARROW_C(THRT, MPD_POS_BUTTON_TB_6_X, MPD_POS_BUTTON_B_Y, 4)
    MPD_TEXT_C(THRT,  MPD_POS_BUTTON_TB_6_X, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC("THRT"))
};