params["_heli"];
#include "\fza_ah64_controls\headers\selections.h"

_heli setobjecttexture [SEL_PL_MPD_BACK, ""];

CLEAR_DIGITS(_heli, SEL_DIGITS_PL_FWD_FUEL);
CLEAR_DIGITS(_heli, SEL_DIGITS_PL_AFT_FUEL);
CLEAR_DIGITS(_heli, SEL_DIGITS_PL_IAFS_FUEL);
CLEAR_DIGITS(_heli, SEL_DIGITS_PL_FLOW1_FUEL);
CLEAR_DIGITS(_heli, SEL_DIGITS_PL_FLOW2_FUEL);
CLEAR_DIGITS(_heli, SEL_DIGITS_PL_TFLOW_FUEL);
CLEAR_DIGITS(_heli, SEL_DIGITS_PL_INT_FUEL);
CLEAR_DIGITS(_heli, SEL_DIGITS_PL_TOT_FUEL);
CLEAR_DIGITS(_heli, SEL_DIGITS_PL_IEND_FUEL);
CLEAR_DIGITS(_heli, SEL_DIGITS_PL_TEND_FUEL);