#define STABILTOR_MODE_ALWAYSENABLED 2
#define STABILTOR_MODE_JOYSTICKONLY 1
#define STABILTOR_MODE_ALWAYSDISABLED 0

#define ISA_STD 0
#define EUROPE_SUMMER 1
#define EUROPE_WINTER 2
#define MIDDLE_EAST 3
#define CENTRAL_ASIA_SUMMER 4
#define CENTRAL_ASIA_WINTER 5
#define ASIA 6