#define SUFFIX ""
#include "code\codes.hpp"
#include "code\barrier.hpp"
#include "code\codeselections.hpp"
#include "code\coderange.hpp"

MPD_TEXT_C(Chan, MPD_POS_BUTTON_TB_1_X, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("CHAN"))
MPD_ARROW_C(Chan, MPD_POS_BUTTON_TB_1_X, MPD_POS_BUTTON_T_Y, 4)

MPD_TEXT_C(Set_Label, MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_T_Y-0.5*MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("SET"))

MPD_TEXT_C(Code, MPD_POS_BUTTON_TB_4_X, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("CODE"))
MPD_ARROW_C(Code, MPD_POS_BUTTON_TB_4_X, MPD_POS_BUTTON_T_Y, 4)
MPD_BOX_TALL_C(Code, MPD_POS_BUTTON_TB_4_X, MPD_POS_BUTTON_T_Y, 4)

MPD_TEXT_C(Freq, MPD_POS_BUTTON_TB_5_X, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("FREQ"))
MPD_ARROW_C(Freq, MPD_POS_BUTTON_TB_5_X, MPD_POS_BUTTON_T_Y, 4)

MPD_TEXT_C(WPN,MPD_POS_BUTTON_TB_1_X,MPD_POS_BUTTON_B_Y,MPD_TEXT_STATIC("WPN"))

class SetCondLRFD {
    condition = C_COND(C_EQ(C_MPD_USER(MFD_IND_CODE_SET), 0));

    MPD_TEXT_C(SetVAB, MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_T_Y+0.5*MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("LRFD"))
    MPD_BOX_C(SetVAB, MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_T_Y+0.5*MPD_TEXT_HEIGHT, 4)

    MPD_TEXT_C(SetBox,0.5,0.19,MPD_TEXT_STATIC("LRFD"))
    class SetBox {
        type=line;
        width=3;
        points[] = {
            MPD_POINTS_BOX_PAD(Null,(0.5-2*MPD_TEXT_WIDTH),0.2,4*MPD_TEXT_WIDTH,MPD_TEXT_HEIGHT-0.02,0.01)
        };
    };
};

class SetCondLST {
    condition = C_COND(C_EQ(C_MPD_USER(MFD_IND_CODE_SET), 1));

    MPD_TEXT_C(SetVAB, MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_T_Y+0.5*MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("LST"))
    MPD_BOX_C(SetVAB, MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_T_Y+0.5*MPD_TEXT_HEIGHT, 3)

    MPD_TEXT_C(SetBox,0.5,0.19,MPD_TEXT_STATIC("LST"))
    class SetBox {
        type=line;
        width=3;
        points[] = {
            MPD_POINTS_BOX_PAD(Null,(0.5-1.5*MPD_TEXT_WIDTH),0.2,3*MPD_TEXT_WIDTH,MPD_TEXT_HEIGHT-0.02,0.01)
        };
    };
};