#define SUFFIX " >"
#include "code\codes.hpp"
#include "code\coderange.hpp"

MPD_ARROW_C(CHAN,MPD_POS_BUTTON_TB_1_X,MPD_POS_BUTTON_T_Y,4)
MPD_TEXT_C(CHAN,MPD_POS_BUTTON_TB_1_X,MPD_POS_BUTTON_T_Y,MPD_TEXT_STATIC("CHAN"))

MPD_ARROW_C(CODE,MPD_POS_BUTTON_TB_4_X,MPD_POS_BUTTON_T_Y,4)
MPD_TEXT_C(CODE,MPD_POS_BUTTON_TB_4_X,MPD_POS_BUTTON_T_Y,MPD_TEXT_STATIC("CODE"))

class PartialIntensity {
    alpha=128;
    MPD_BOX_TALL_C(CODE,MPD_POS_BUTTON_TB_4_X,MPD_POS_BUTTON_T_Y,4)
};
MPD_ARROW_C(FREQ,MPD_POS_BUTTON_TB_5_X,MPD_POS_BUTTON_T_Y,4)
MPD_TEXT_C(FREQ,MPD_POS_BUTTON_TB_5_X,MPD_POS_BUTTON_T_Y,MPD_TEXT_STATIC("FREQ"))
MPD_BOX_TALL_C(FREQ,MPD_POS_BUTTON_TB_5_X,MPD_POS_BUTTON_T_Y,4)

MPD_TEXT_C(WPN,MPD_POS_BUTTON_TB_1_X,MPD_POS_BUTTON_B_Y,MPD_TEXT_STATIC("WPN"))
