#include "\fza_ah64_mpd\headers\mfdConstants.h"

//MPD_BOX_BAR_T(FAULT, MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_T_Y)

//T1
MPD_ARROW_C(DTU, MPD_POS_BUTTON_TB_1_X, MPD_POS_BUTTON_T_Y, 3)
MPD_TEXT_C(DTU, MPD_POS_BUTTON_TB_1_X, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("DTU"))
//T2
MPD_BOX_BAR_T(FAULT, MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_T_Y)
MPD_TEXT_C(FAULT,    MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("FAULT"))
//T3
MPD_BOX_BAR_T(IBIT, MPD_POS_BUTTON_TB_3_X, MPD_POS_BUTTON_T_Y)
MPD_TEXT_C(IBIT, MPD_POS_BUTTON_TB_3_X, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("IBIT"))

//T5
MPD_TEXT_C(VERS, MPD_POS_BUTTON_TB_5_X, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("VERS"))
MPD_BOX_TALL_C(VERS, MPD_POS_BUTTON_TB_5_X, MPD_POS_BUTTON_T_Y, 4)
//T6
MPD_ARROW_C(UTIL, MPD_POS_BUTTON_TB_6_X, MPD_POS_BUTTON_T_Y, 4)
MPD_TEXT_C(UTIL, MPD_POS_BUTTON_TB_6_X, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("UTIL"))

//B1
MPD_BOX_C(WPT,  MPD_POS_BUTTON_TB_1_X, MPD_POS_BUTTON_B_Y, 3)
MPD_TEXT_C(DMS, MPD_POS_BUTTON_TB_1_X, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC("DMS"))
//B6
MPD_ARROW_C(VER, MPD_POS_BUTTON_TB_6_X, MPD_POS_BUTTON_B_Y, 3)
MPD_TEXT_C(VER, MPD_POS_BUTTON_TB_6_X, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC("VER"))
MPD_BOX_TALL_C(VER, MPD_POS_BUTTON_TB_6_X, MPD_POS_BUTTON_B_Y, 3)

//Title Box
MPD_TEXT_C(ABBREVIATIONS, 0.5, 0.09, MPD_TEXT_STATIC("SOFTWARE VERSIONS"))
class lines {
    type = line;
    width = 3;
    points[] = {
        MPD_POINTS_BOX(Null, (0.5 - MPD_TEXT_WIDTH * 8.5), 0.09, (17.5 * MPD_TEXT_WIDTH), MPD_TEXT_HEIGHT)
    };
};

#define MPD_VER_COLUMN_1_X (0.49 - 18 * MPD_TEXT_WIDTH)
#define MPD_VER_COLUMN_2_X 0.52
#define MPD_VER_COLUMN_Y 0.15
#define MPD_VER_COLUMN_SPACING (MPD_TEXT_HEIGHT * 0.90)

#define MPD_VER_ITEM_L(INDEX,STATE,COLOUR) \
class VerItem_L_##INDEX##_##STATE { \
    condition = C_COND(C_EQ(C_MPD_USER(INDEX),STATE)); \
    color[] = COLOUR; \
    MPD_TEXT_R(ColumnText, MPD_VER_COLUMN_1_X, (MPD_VER_COLUMN_Y + (INDEX * MPD_VER_COLUMN_SPACING)), MPD_TEXT_USER(INDEX)) \
};

#define MPD_VER_ITEM_R(INDEX,STATE,COLOUR) \
class VerItem_R_##INDEX##_##STATE { \
    condition = C_COND(C_EQ(C_MPD_USER(INDEX),STATE)); \
    color[] = COLOUR; \
    MPD_TEXT_R(ColumnText, MPD_VER_COLUMN_2_X, (MPD_VER_COLUMN_Y + ((INDEX - 19) * MPD_VER_COLUMN_SPACING)), MPD_TEXT_USER(INDEX)) \
};

#define MPD_VER_L(INDEX) \
    MPD_VER_ITEM_L(INDEX,0,MPD_COLOUR_GREEN) \
    MPD_VER_ITEM_L(INDEX,1,MPD_COLOUR_YELLOW) \
    MPD_VER_ITEM_L(INDEX,2,MPD_COLOUR_RED)

#define MPD_VER_R(INDEX) \
    MPD_VER_ITEM_R(INDEX,0,MPD_COLOUR_GREEN) \
    MPD_VER_ITEM_R(INDEX,1,MPD_COLOUR_YELLOW) \
    MPD_VER_ITEM_R(INDEX,2,MPD_COLOUR_RED)
    
class SoftwareInfoDisplay {
    MPD_VER_L(0)
    MPD_VER_L(1)
    MPD_VER_L(2)
    MPD_VER_L(3)
    MPD_VER_L(4)
    MPD_VER_L(5)
    MPD_VER_L(6)
    MPD_VER_L(7)
    MPD_VER_L(8)
    MPD_VER_L(9)
    MPD_VER_L(10)
    MPD_VER_L(11)
    MPD_VER_L(12)
    MPD_VER_L(13)
    MPD_VER_L(14)
    MPD_VER_L(15)
    MPD_VER_L(16)
    MPD_VER_L(17)
    MPD_VER_L(18)
    MPD_VER_R(19)
    MPD_VER_R(20)
    MPD_VER_R(21)
    MPD_VER_R(22)
    MPD_VER_R(23)
    MPD_VER_R(24)
    MPD_VER_R(25)
    MPD_VER_R(26)
    MPD_VER_R(27)
    MPD_VER_R(28)
    MPD_VER_R(29)
    MPD_VER_R(30)
    MPD_VER_R(31)
    MPD_VER_R(32)
    MPD_VER_R(33)
    MPD_VER_R(34)
    MPD_VER_R(35)
    MPD_VER_R(36)
    MPD_VER_R(37)
};