#define RPM_OFF 0
#define RPM_IDLE 14776
#define RPM_FLY 21109

#define ENGINE_STATE_LEN_OFFSTARTED 10
#define ENGINE_STATE_LEN_STARTEDOFF 10
#define ENGINE_STATE_LEN_STARTEDIDLE 86
#define ENGINE_STATE_LEN_IDLEOFF 30
#define ENGINE_STATE_LEN_IDLEFLY 22
#define ENGINE_STATE_LEN_FLYIDLE 20

#define ENGINE_STATE_STARTEDIDLE_ROTOR_DELAY 10

#define ENGINE_STATE_USING_STARTER ["OFFSTARTED", "STARTED"]

#define ENGINE_CONTROL_STARTER -1
#define ENGINE_CONTROL_THROTTLE_OFF 0
#define ENGINE_CONTROL_THROTTLE_IDLE 1
#define ENGINE_CONTROL_THROTTLE_FLY 2