hiddenselections[]={ "skin",
	"skin_fcr",
	"ufd_back",
	"in_lt_apu",
	"mpd_brt",
	"in_backlight",
	"in_backlight2",
	"in_lt_fire1",
	"in_lt_fire1rdy",
	"in_lt_fire2",
	"in_lt_fire2rdy",
	"in_lt_fireapu",
	"in_lt_fireapurdy",
	"in_lt_firepdis",
	"in_lt_firerdis",
	"in_lt_mstrcau",
	"in_lt_mstrwrn",
#define SECTION(val) \
	GLUE(val,_digit01),\
	GLUE(val,_digit02),\
	GLUE(val,_digit03),\
	GLUE(val,_digit04),\
	GLUE(val,_digit05),\
	GLUE(val,_digit06),\
	GLUE(val,_digit07),\
	GLUE(val,_digit08),\
	GLUE(val,_digit09),\
	GLUE(val,_digit10),\
	GLUE(val,_digit11),\
	GLUE(val,_digit12),\
	GLUE(val,_digit13),\
	GLUE(val,_digit14),\
	GLUE(val,_digit15),\
	GLUE(val,_icon),
	LIST_OF_BONES(pl)
	LIST_OF_BONES(pr)
	"pl_mpd_back",
	"pr_mpd_back",
	"pl_mpd_tsd",
	"pr_mpd_tsd",
};