MPD_TEXT_C(Title, 0.5, 0.105, MPD_TEXT_STATIC("MINI GAMES"))

///////////////// L ///////////////
//L1
MPD_ARROW_R(L1,   MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_1_Y, 3)
MPD_TEXT_R(L1,    MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_1_Y, MPD_TEXT_STATIC("ASTEROIDS"))
//L2
MPD_ARROW_R(L2,   MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_2_Y, 3)
MPD_TEXT_R(L2,    MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_2_Y, MPD_TEXT_STATIC("SPACE INV"))
//L3
MPD_ARROW_R(L3,   MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_3_Y, 3)
MPD_TEXT_R(L3,    MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_3_Y, MPD_TEXT_STATIC("PONG"))
//L4-L6: reserved for future minigames

///////////////// R ///////////////
//R1-R6: reserved for future minigames

///////////////// B ///////////////
//B1
MPD_ARROW_C(DMS, MPD_POS_BUTTON_TB_1_X, MPD_POS_BUTTON_B_Y, 3)
MPD_TEXT_C(DMS,  MPD_POS_BUTTON_TB_1_X, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC("DMS"))
