MPD_TEXT_C(Title, 0.5, 0.105, MPD_TEXT_STATIC("MINI GAMES"))

///////////////// L /////////////// (single-player)
//L1
MPD_ARROW_R(L1,   MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_1_Y, 3)
MPD_TEXT_R(L1,    MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_1_Y, MPD_TEXT_STATIC("ASTEROIDS"))
//L2
MPD_ARROW_R(L2,   MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_2_Y, 3)
MPD_TEXT_R(L2,    MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_2_Y, MPD_TEXT_STATIC("SPACE INV"))
//L3
MPD_ARROW_R(L3,   MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_3_Y, 3)
MPD_TEXT_R(L3,    MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_3_Y, MPD_TEXT_STATIC("BREAKOUT"))
//L4
MPD_ARROW_R(L4,   MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_4_Y, 3)
MPD_TEXT_R(L4,    MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_4_Y, MPD_TEXT_STATIC("LUNAR LDR"))

///////////////// R /////////////// (multiplayer)
//R1
MPD_ARROW_L(R1,   MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_1_Y, 3)
MPD_TEXT_L(R1,    MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_1_Y, MPD_TEXT_STATIC("PONG"))
//R2
MPD_ARROW_L(R2,   MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_2_Y, 3)
MPD_TEXT_L(R2,    MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_2_Y, MPD_TEXT_STATIC("BATTLESHIP"))
//R3
MPD_ARROW_L(R3,   MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_3_Y, 3)
MPD_TEXT_L(R3,    MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_3_Y, MPD_TEXT_STATIC("TIC TAC TOE"))
//R4
MPD_ARROW_L(R4,   MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_4_Y, 3)
MPD_TEXT_L(R4,    MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_4_Y, MPD_TEXT_STATIC("CONNECT 4"))
//R5
MPD_ARROW_L(R5,   MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_5_Y, 3)
MPD_TEXT_L(R5,    MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_5_Y, MPD_TEXT_STATIC("ROCK PAPER"))
//R6
MPD_ARROW_L(R6,   MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_6_Y, 3)
MPD_TEXT_L(R6,    MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_6_Y, MPD_TEXT_STATIC("CHECKERS"))

///////////////// B ///////////////
//B1
MPD_ARROW_C(DMS, MPD_POS_BUTTON_TB_1_X, MPD_POS_BUTTON_B_Y, 3)
MPD_TEXT_C(DMS,  MPD_POS_BUTTON_TB_1_X, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC("DMS"))

//B2 - only drawn if fza_ah64_doom is loaded (fn_init.sqf sets MFD_IND_MINIGAMES_DOOM_AVAILABLE once, never changes mid-session)
class DoomAvailable {
    condition = C_COND(C_MPD_USER(MFD_IND_MINIGAMES_DOOM_AVAILABLE));
    MPD_ARROW_R(B2,   MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_B_Y, 3)
    MPD_TEXT_R(B2,    MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC("DOOM"))
};
