#define MPD_ICON_TYPE_A 0
#define MPD_ICON_TYPE_B 1
#define MPD_ICON_TYPE_C 2
#define MPD_ICON_TYPE_D 3
#define MPD_ICON_TYPE_E 4
#define MPD_ICON_TYPE_F 5
#define MPD_ICON_TYPE_G 6

#define MPD_ICON_TEXT_ID 0
#define MPD_ICON_TEXT_FREE 1

#define POINT_TYPE_WP 0
#define POINT_TYPE_HZ 1
#define POINT_TYPE_CM 2
#define POINT_TYPE_BFT 3
#define POINT_TYPE_TG 4
#define POINT_TYPE_FCR 5
#define POINT_TYPE_ASE 6

#define POINT_COUNT_WP_HZ 50
#define POINT_COUNT_CM 49
#define POINT_COUNT_TG_TH 50

#define POINT_GET_ARMA_POS 1
#define POINT_GET_FREE_TEXT 2
#define POINT_GET_TYPE 3
#define POINT_GET_ID 4
#define POINT_GET_IDENT 5
#define POINT_GET_GRID_COORD 6
#define POINT_GET_LAT_LONG 7
#define POINT_GET_ALT_MSL 8
#define POINT_GET_ALT_AGL 9
#define POINT_GET_FULL [0,10]

#define POINT_SET_FREE_TEXT 0
#define POINT_SET_ARMA_POS 1
#define POINT_SET_ALT_MSL 2
#define POINT_SET_IDENT 3

#define MPD_ICON_COLOR_GREEN {0.0, 1.0, 0.5, 1}
#define MPD_ICON_COLOR_BLUE {0.4, 0.6, 1.0, 1}
#define MPD_ICON_COLOR_RED {1.0, 0.0, 0.2, 1}
#define MPD_ICON_COLOR_YELLOW {1.0, 1.0, 0.0, 1}

#define MPD_POSMODE_WORLD true
#define MPD_POSMODE_SCREEN false