#define MPD_ICON_TYPE_A 0
#define MPD_ICON_TYPE_B 1
#define MPD_ICON_TYPE_C 2
#define MPD_ICON_TYPE_D 3
#define MPD_ICON_TYPE_E 4
#define MPD_ICON_TYPE_F 5
#define MPD_ICON_TYPE_G 6

#define POINT_TYPE_WP 0
#define POINT_TYPE_HZ 1
#define POINT_TYPE_CM 2
#define POINT_TYPE_TG 3

#define POINT_COUNT_WP_HZ 50
#define POINT_COUNT_CM 49
#define POINT_COUNT_TG_TH 50

#define POINT_GET_IDENT 0
#define POINT_GET_FREE_TEXT 1
#define POINT_GET_TYPE 2
#define POINT_GET_ICON_TEX 3
#define POINT_GET_ICON_OFFSET 4
#define POINT_GET_ICON_TYPE 5
#define POINT_GET_ARMA_POS 6
#define POINT_GET_GRID_COORD 7
#define POINT_GET_LAT_LONG 8
#define POINT_GET_ALT_MSL 9
#define POINT_GET_ALT_AGL 10
#define POINT_GET_FULL [0,11]

#define POINT_SET_FREE_TEXT 0
#define POINT_SET_ARMA_POS 1
#define POINT_SET_ALT_MSL 2