name = "AH-64D Apache Longbow"
prefix = "fza_ah64"
mainprefix = "x"

[properties]
author = "AH-64 Development team"

[version]
major = 2
minor = 3
patch = 0
build = 1
git_hash = 0

[files]
include = [
    "mod.cpp",
    "apache_mod_logo.paa",
    "apache_mod_picture.paa",
    "LICENSE",
    "Readme.md",
]

[hemtt.release]
sign = true
archive = true
