# generate_sil_data.ps1
# Reads PNG source files from addons/fza_ah64_missionplanner/ui/img/
# and regenerates ui/sil_data.js with embedded base64 data URIs.
#
# Run this whenever silhouette artwork (PNG files) are updated:
#   .\tools\generate_sil_data.ps1
#
# The generated sil_data.js is committed to the repository.
# The HEMTT pre_build hook (inline_planner_js.rhai) inlines it into
# the self-contained planner.html before packing.

$imgDir  = "$PSScriptRoot\..\addons\fza_ah64_missionplanner\ui\img"
$outFile = "$PSScriptRoot\..\addons\fza_ah64_missionplanner\ui\sil_data.js"

# Map: JS key -> PNG filename
# Keys must match _silData.* references in weapons.js
$imageMap = [ordered]@{
    "empty"             = "empty.png"
    "fcr"               = "fcr.png"
    "pylon1_m299_empty" = "pylon1_m299_empty.png"
    "pylon1_m261"       = "pylon1_m261.png"
    "pylon1_auxTank"    = "pylon1_auxTank.png"
    "pylon2_m299"       = "pylon2_m299.png"
    "pylon2_m261"       = "pylon2_m261.png"
    "pylon2_auxTank"    = "pylon2_auxTank.png"
    "pylon3_m299"       = "pylon3_m299.png"
    "pylon3_m261"       = "pylon3_m261.png"
    "pylon3_auxTank"    = "pylon3_auxTank.png"
    "pylon4_m299_empty" = "pylon4_m299_empty.png"
    "pylon4_m261"       = "pylon4_m261.png"
    "pylon4_auxTank"    = "pylon4_auxTank.png"
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("// Silhouette image data URIs - generated by tools/generate_sil_data.ps1")
$lines.Add("// Do not edit manually. Re-run the script when PNG source files change.")
$lines.Add("var _silData = {")

$keys  = @($imageMap.Keys)
$count = $keys.Count

for ($i = 0; $i -lt $count; $i++) {
    $key   = $keys[$i]
    $fname = $imageMap[$key]
    $path  = Join-Path $imgDir $fname

    if (-not (Test-Path $path)) {
        Write-Error "Missing source file: $path"
        exit 1
    }

    $bytes = [System.IO.File]::ReadAllBytes($path)
    $b64   = [System.Convert]::ToBase64String($bytes)
    $comma = if ($i -lt ($count - 1)) { "," } else { "" }
    $lines.Add("  ${key}: 'data:image/png;base64,${b64}'${comma}")
}

$lines.Add("};")

$content = [string]::Join("`n", $lines) + "`n"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($outFile, $content, $utf8NoBom)

Write-Host ("Generated " + $outFile + " (" + $count + " images)") -ForegroundColor Green
