#ifndef SELECTIONS_H
#define SELECTIONS_H
//These were autogenerated from config files
#define SEL_SKIN 0
#define SEL_SKIN_FCR 1
#define SEL_UFD_BACK 2
#define SEL_IN_LT_APU 3
#define SEL_MPD_BRT 4
#define SEL_IN_BACKLIGHT 5
#define SEL_IN_BACKLIGHT2 6
#define SEL_IN_LT_FIRE1 7
#define SEL_IN_LT_FIRE1RDY 8
#define SEL_IN_LT_FIRE2 9
#define SEL_IN_LT_FIRE2RDY 10
#define SEL_IN_LT_FIREAPU 11
#define SEL_IN_LT_FIREAPURDY 12
#define SEL_IN_LT_FIREPDIS 13
#define SEL_IN_LT_FIRERDIS 14
#define SEL_IN_LT_MSTRCAU 15
#define SEL_IN_LT_MSTRWRN 16
#endif
