MPD_TEXT_R(Chan_A_Code,MPD_POS_BUTTON_L_X,MPD_POS_BUTTON_LR_1_Y-0.5*MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("A"+SUFFIX)))
MPD_TEXT_R(Chan_A_Freq,MPD_POS_BUTTON_L_X,MPD_POS_BUTTON_LR_1_Y+0.5*MPD_TEXT_HEIGHT,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_A))

MPD_TEXT_R(Chan_B_Code,MPD_POS_BUTTON_L_X,MPD_POS_BUTTON_LR_2_Y-0.5*MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("B"+SUFFIX)))
MPD_TEXT_R(Chan_B_Freq,MPD_POS_BUTTON_L_X,MPD_POS_BUTTON_LR_2_Y+0.5*MPD_TEXT_HEIGHT,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_B))

MPD_TEXT_R(Chan_C_Code,MPD_POS_BUTTON_L_X,MPD_POS_BUTTON_LR_3_Y-0.5*MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("C"+SUFFIX)))
MPD_TEXT_R(Chan_C_Freq,MPD_POS_BUTTON_L_X,MPD_POS_BUTTON_LR_3_Y+0.5*MPD_TEXT_HEIGHT,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_C))

MPD_TEXT_R(Chan_D_Code,MPD_POS_BUTTON_L_X,MPD_POS_BUTTON_LR_4_Y-0.5*MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("D"+SUFFIX)))
MPD_TEXT_R(Chan_D_Freq,MPD_POS_BUTTON_L_X,MPD_POS_BUTTON_LR_4_Y+0.5*MPD_TEXT_HEIGHT,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_D))

MPD_TEXT_R(Chan_E_Code,MPD_POS_BUTTON_L_X,MPD_POS_BUTTON_LR_5_Y-0.5*MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("E"+SUFFIX)))
MPD_TEXT_R(Chan_E_Freq,MPD_POS_BUTTON_L_X,MPD_POS_BUTTON_LR_5_Y+0.5*MPD_TEXT_HEIGHT,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_E))

MPD_TEXT_R(Chan_F_Code,MPD_POS_BUTTON_L_X,MPD_POS_BUTTON_LR_6_Y-0.5*MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("F"+SUFFIX)))
MPD_TEXT_R(Chan_F_Freq,MPD_POS_BUTTON_L_X,MPD_POS_BUTTON_LR_6_Y+0.5*MPD_TEXT_HEIGHT,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_F))

MPD_TEXT_C(Chan_G_Code,MPD_POS_BUTTON_TB_2_X,MPD_POS_BUTTON_B_Y-MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("G"+SUFFIX)))
MPD_TEXT_C(Chan_G_Freq,MPD_POS_BUTTON_TB_2_X,MPD_POS_BUTTON_B_Y                      ,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_G))

MPD_TEXT_C(Chan_H_Code,MPD_POS_BUTTON_TB_3_X,MPD_POS_BUTTON_B_Y-MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("H"+SUFFIX)))
MPD_TEXT_C(Chan_H_Freq,MPD_POS_BUTTON_TB_3_X,MPD_POS_BUTTON_B_Y                      ,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_H))

MPD_TEXT_C(Chan_J_Code,MPD_POS_BUTTON_TB_4_X,MPD_POS_BUTTON_B_Y-MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("J"+SUFFIX)))
MPD_TEXT_C(Chan_J_Freq,MPD_POS_BUTTON_TB_4_X,MPD_POS_BUTTON_B_Y                      ,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_J))

MPD_TEXT_C(Chan_K_Code,MPD_POS_BUTTON_TB_5_X,MPD_POS_BUTTON_B_Y-MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("K"+SUFFIX)))
MPD_TEXT_C(Chan_K_Freq,MPD_POS_BUTTON_TB_5_X,MPD_POS_BUTTON_B_Y                      ,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_K))

MPD_TEXT_L(Chan_L_Code,MPD_POS_BUTTON_R_X,MPD_POS_BUTTON_LR_6_Y-0.5*MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("L"+SUFFIX)))
MPD_TEXT_L(Chan_L_Freq,MPD_POS_BUTTON_R_X,MPD_POS_BUTTON_LR_6_Y+0.5*MPD_TEXT_HEIGHT,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_L))

MPD_TEXT_L(Chan_M_Code,MPD_POS_BUTTON_R_X,MPD_POS_BUTTON_LR_5_Y-0.5*MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("M"+SUFFIX)))
MPD_TEXT_L(Chan_M_Freq,MPD_POS_BUTTON_R_X,MPD_POS_BUTTON_LR_5_Y+0.5*MPD_TEXT_HEIGHT,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_M))

MPD_TEXT_L(Chan_N_Code,MPD_POS_BUTTON_R_X,MPD_POS_BUTTON_LR_4_Y-0.5*MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("N"+SUFFIX)))
MPD_TEXT_L(Chan_N_Freq,MPD_POS_BUTTON_R_X,MPD_POS_BUTTON_LR_4_Y+0.5*MPD_TEXT_HEIGHT,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_N))

MPD_TEXT_L(Chan_P_Code,MPD_POS_BUTTON_R_X,MPD_POS_BUTTON_LR_3_Y-0.5*MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("P"+SUFFIX)))
MPD_TEXT_L(Chan_P_Freq,MPD_POS_BUTTON_R_X,MPD_POS_BUTTON_LR_3_Y+0.5*MPD_TEXT_HEIGHT,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_P))

MPD_TEXT_L(Chan_Q_Code,MPD_POS_BUTTON_R_X,MPD_POS_BUTTON_LR_2_Y-0.5*MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("Q"+SUFFIX)))
MPD_TEXT_L(Chan_Q_Freq,MPD_POS_BUTTON_R_X,MPD_POS_BUTTON_LR_2_Y+0.5*MPD_TEXT_HEIGHT,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_Q))

MPD_TEXT_L(Chan_R_Code,MPD_POS_BUTTON_R_X,MPD_POS_BUTTON_LR_1_Y-0.5*MPD_TEXT_HEIGHT,MPD_TEXT_STATIC(__EVAL("R"+SUFFIX)))
MPD_TEXT_L(Chan_R_Freq,MPD_POS_BUTTON_R_X,MPD_POS_BUTTON_LR_1_Y+0.5*MPD_TEXT_HEIGHT,MPD_TEXT_USER(MFD_TEXT_IND_FREQ_R))