#define MPD_CODE_SELECTION(letter,num,text) class CodeSelection##letter { \
    condition = C_COND(C_EQ(C_MPD_USER(MFD_IND_CODE_SELECTED), num)); \
    text \
}

MPD_CODE_SELECTION(A,0,MPD_BOX_R(Sel,MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_1_Y-0.5*MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(B,1,MPD_BOX_R(Sel,MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_2_Y-0.5*MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(C,2,MPD_BOX_R(Sel,MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_3_Y-0.5*MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(D,3,MPD_BOX_R(Sel,MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_4_Y-0.5*MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(E,4,MPD_BOX_R(Sel,MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_5_Y-0.5*MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(F,5,MPD_BOX_R(Sel,MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_6_Y-0.5*MPD_TEXT_HEIGHT, 1))

MPD_CODE_SELECTION(G,6,MPD_BOX_C(Sel,MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_B_Y-MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(H,7,MPD_BOX_C(Sel,MPD_POS_BUTTON_TB_3_X, MPD_POS_BUTTON_B_Y-MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(J,8,MPD_BOX_C(Sel,MPD_POS_BUTTON_TB_4_X, MPD_POS_BUTTON_B_Y-MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(K,9,MPD_BOX_C(Sel,MPD_POS_BUTTON_TB_5_X, MPD_POS_BUTTON_B_Y-MPD_TEXT_HEIGHT, 1))

MPD_CODE_SELECTION(L,10,MPD_BOX_L(Sel,MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_6_Y-0.5*MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(M,11,MPD_BOX_L(Sel,MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_5_Y-0.5*MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(N,12,MPD_BOX_L(Sel,MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_4_Y-0.5*MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(P,13,MPD_BOX_L(Sel,MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_3_Y-0.5*MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(Q,14,MPD_BOX_L(Sel,MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_2_Y-0.5*MPD_TEXT_HEIGHT, 1))
MPD_CODE_SELECTION(R,15,MPD_BOX_L(Sel,MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_1_Y-0.5*MPD_TEXT_HEIGHT, 1))