name: Document code
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
    - name: Generate MFD indices documentation
      run: python tools/mfd_documentation/document.py --output=docs/other/mfdindices.html
    - name: Generate naturaldocs
      uses: mattysmith22/Naturaldocs-github-action@master
      with:
        output-dir: docs
        project-config-dir: naturaldocs
    - name: Push documentation to pages
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
